---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lastmile/public_html/
    - /bin/cp dist/index.html $DEPLOYPATH
    - /bin/cp dist/logo.png $DEPLOYPATH
    - /bin/cp -R dist/assets $DEPLOYPATH
