---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hh0h355mndjv/public_html
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/cp -f dist/index.html $DEPLOYPATH/
    - /bin/cp -f dist/logo.png $DEPLOYPATH/
    - /bin/cp -f dist/assets/* $DEPLOYPATH/assets/
