---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hh0h355mndjv/public_html
    - /bin/cp dist/index.html $DEPLOYPATH/index.html
    - /bin/cp dist/logo.png $DEPLOYPATH/logo.png
    - /bin/cp -r dist/assets $DEPLOYPATH/
